name: Update Changelog
on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'

permissions:
  contents: write
  pull-requests: read

jobs:
  update-changelog:
    uses: Azure/tfmod-scaffold/.github/workflows/update-changelog.yaml@main
